//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranVanDuc_2122110512.Context
{
    using System;
    using System.Collections.Generic;

    public class Order
    {
        public string Delivery_name { get; set; }
        public string Delivery_gender { get; set; }
        public string Delivery_email { get; set; }
        public string Delivery_phone { get; set; }
        public string Delivery_address { get; set; }
        public string Note { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public long OrderId { get; set; } // Sửa kiểu dữ liệu thành long
        public long CustomerId { get; set; } // Sửa kiểu dữ liệu thành long
        public decimal TotalAmount { get; set; } // Đảm bảo thuộc tính này tồn tại
        public DateTime OrderDate { get; set; } // Đảm bảo thuộc tính này tồn tại
        public virtual Customer Customer { get; set; }
        public string ShippingAddress { get; set; } // Đảm bảo thuộc tính này tồn tại   
        public string PaymentMethod { get; set; } // Đảm bảo thuộc tính này tồn tại
    }
}
