


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranVanDuc_2122110512.Context
{
    using System;
    using System.Collections.Generic;

    public class Post
    {
        public int PostId { get; set; } // Cột [PostId]
        public string Title { get; set; } // Cột [Title]
        public string Content { get; set; } // Cột [Content]
        public DateTime? CreatedDate { get; set; } // Cột [CreatedDate]
        public int? TopicId { get; set; } // Cột [TopicId]
        public string ImageUrl { get; set; } // Cột [ImageUrl]
                                             // Khai báo quan hệ
        public virtual Topic Topic { get; set; }
    }
}
