//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranVanDuc_2122110512.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int QuantityInStock { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> OrderId { get; set; }
    }
}
